sudo: false
language: ruby
cache: bundler
rvm:
- 2.7.0
before_install: gem install bundler -v 2.1.2
script: bundle exec rspec
deploy:
  provider: rubygems
  api_key:
    secure:
  gem: coloregex
  on:
    tags: true
    repo: khalilgharbaoui/coloregex
